// Code generated by lipmark-tinted; DO NOT EDIT.

package embedded

import (
	"sort"

	"github.com/pmarschik/lipmark/theme"
	"github.com/pmarschik/lipmark/theme/tinted"
)

// CatppuccinMochaPalette contains the "Catppuccin Mocha" palette colors (base24, dark).
// Author: https://github.com/catppuccin/catppuccin
var CatppuccinMochaPalette = tinted.PaletteDefs{
	Base00: theme.StyleDef{Foreground: "#1e1e2e"},
	Base01: theme.StyleDef{Foreground: "#181825"},
	Base02: theme.StyleDef{Foreground: "#313244"},
	Base03: theme.StyleDef{Foreground: "#45475a"},
	Base04: theme.StyleDef{Foreground: "#585b70"},
	Base05: theme.StyleDef{Foreground: "#cdd6f4"},
	Base06: theme.StyleDef{Foreground: "#f5e0dc"},
	Base07: theme.StyleDef{Foreground: "#b4befe"},
	Base08: theme.StyleDef{Foreground: "#f38ba8"},
	Base09: theme.StyleDef{Foreground: "#fab387"},
	Base0A: theme.StyleDef{Foreground: "#f9e2af"},
	Base0B: theme.StyleDef{Foreground: "#a6e3a1"},
	Base0C: theme.StyleDef{Foreground: "#94e2d5"},
	Base0D: theme.StyleDef{Foreground: "#89b4fa"},
	Base0E: theme.StyleDef{Foreground: "#cba6f7"},
	Base0F: theme.StyleDef{Foreground: "#f2cdcd"},
	Base10: theme.StyleDef{Foreground: "#181825"},
	Base11: theme.StyleDef{Foreground: "#11111b"},
	Base12: theme.StyleDef{Foreground: "#eba0ac"},
	Base13: theme.StyleDef{Foreground: "#f5e0dc"},
	Base14: theme.StyleDef{Foreground: "#a6e3a1"},
	Base15: theme.StyleDef{Foreground: "#89dceb"},
	Base16: theme.StyleDef{Foreground: "#74c7ec"},
	Base17: theme.StyleDef{Foreground: "#f5c2e7"},
}

// CatppuccinMocha contains the "Catppuccin Mocha" base styles.
var CatppuccinMocha = theme.BaseStyleDefs{
	Bold: theme.StyleDef{Foreground: CatppuccinMochaPalette.Base05.Foreground, Bold: true},
	Dim: theme.StyleDef{Foreground: CatppuccinMochaPalette.Base03.Foreground, Faint: true},
	Italic: theme.StyleDef{Foreground: CatppuccinMochaPalette.Base05.Foreground, Italic: true},
	Success: theme.StyleDef{Foreground: CatppuccinMochaPalette.Base0B.Foreground, Bold: true},
	Error: theme.StyleDef{Foreground: CatppuccinMochaPalette.Base08.Foreground, Bold: true},
	Warning: theme.StyleDef{Foreground: CatppuccinMochaPalette.Base0A.Foreground, Bold: true},
	Info: theme.StyleDef{Foreground: CatppuccinMochaPalette.Base0D.Foreground},
	Muted: theme.StyleDef{Foreground: CatppuccinMochaPalette.Base04.Foreground},
	Command: theme.StyleDef{Foreground: CatppuccinMochaPalette.Base0C.Foreground},
	Flag: theme.StyleDef{Foreground: CatppuccinMochaPalette.Base04.Foreground},
	Heading: theme.StyleDef{Foreground: CatppuccinMochaPalette.Base0E.Foreground, Bold: true},
	Key: theme.StyleDef{Foreground: CatppuccinMochaPalette.Base0C.Foreground},
	Path: theme.StyleDef{Foreground: CatppuccinMochaPalette.Base04.Foreground},
}

// DraculaPalette contains the "Dracula" palette colors (base24, dark).
// Author: FredHappyface (https://github.com/fredHappyface)
var DraculaPalette = tinted.PaletteDefs{
	Base00: theme.StyleDef{Foreground: "#282a36"},
	Base01: theme.StyleDef{Foreground: "#363447"},
	Base02: theme.StyleDef{Foreground: "#44475a"},
	Base03: theme.StyleDef{Foreground: "#6272a4"},
	Base04: theme.StyleDef{Foreground: "#9ea8c7"},
	Base05: theme.StyleDef{Foreground: "#f8f8f2"},
	Base06: theme.StyleDef{Foreground: "#f0f1f4"},
	Base07: theme.StyleDef{Foreground: "#ffffff"},
	Base08: theme.StyleDef{Foreground: "#ff5555"},
	Base09: theme.StyleDef{Foreground: "#ffb86c"},
	Base0A: theme.StyleDef{Foreground: "#f1fa8c"},
	Base0B: theme.StyleDef{Foreground: "#50fa7b"},
	Base0C: theme.StyleDef{Foreground: "#8be9fd"},
	Base0D: theme.StyleDef{Foreground: "#80bfff"},
	Base0E: theme.StyleDef{Foreground: "#ff79c6"},
	Base0F: theme.StyleDef{Foreground: "#bd93f9"},
	Base10: theme.StyleDef{Foreground: "#1e2029"},
	Base11: theme.StyleDef{Foreground: "#16171d"},
	Base12: theme.StyleDef{Foreground: "#f28c8c"},
	Base13: theme.StyleDef{Foreground: "#eef5a3"},
	Base14: theme.StyleDef{Foreground: "#a3f5b8"},
	Base15: theme.StyleDef{Foreground: "#baedf7"},
	Base16: theme.StyleDef{Foreground: "#a3ccf5"},
	Base17: theme.StyleDef{Foreground: "#f5a3d2"},
}

// Dracula contains the "Dracula" base styles.
var Dracula = theme.BaseStyleDefs{
	Bold: theme.StyleDef{Foreground: DraculaPalette.Base05.Foreground, Bold: true},
	Dim: theme.StyleDef{Foreground: DraculaPalette.Base03.Foreground, Faint: true},
	Italic: theme.StyleDef{Foreground: DraculaPalette.Base05.Foreground, Italic: true},
	Success: theme.StyleDef{Foreground: DraculaPalette.Base0B.Foreground, Bold: true},
	Error: theme.StyleDef{Foreground: DraculaPalette.Base08.Foreground, Bold: true},
	Warning: theme.StyleDef{Foreground: DraculaPalette.Base0A.Foreground, Bold: true},
	Info: theme.StyleDef{Foreground: DraculaPalette.Base0D.Foreground},
	Muted: theme.StyleDef{Foreground: DraculaPalette.Base04.Foreground},
	Command: theme.StyleDef{Foreground: DraculaPalette.Base0C.Foreground},
	Flag: theme.StyleDef{Foreground: DraculaPalette.Base04.Foreground},
	Heading: theme.StyleDef{Foreground: DraculaPalette.Base0E.Foreground, Bold: true},
	Key: theme.StyleDef{Foreground: DraculaPalette.Base0C.Foreground},
	Path: theme.StyleDef{Foreground: DraculaPalette.Base04.Foreground},
}

// NordPalette contains the "Nord" palette colors (base16, dark).
// Author: arcticicestudio
var NordPalette = tinted.PaletteDefs{
	Base00: theme.StyleDef{Foreground: "#2E3440"},
	Base01: theme.StyleDef{Foreground: "#3B4252"},
	Base02: theme.StyleDef{Foreground: "#434C5E"},
	Base03: theme.StyleDef{Foreground: "#4C566A"},
	Base04: theme.StyleDef{Foreground: "#D8DEE9"},
	Base05: theme.StyleDef{Foreground: "#E5E9F0"},
	Base06: theme.StyleDef{Foreground: "#ECEFF4"},
	Base07: theme.StyleDef{Foreground: "#8FBCBB"},
	Base08: theme.StyleDef{Foreground: "#BF616A"},
	Base09: theme.StyleDef{Foreground: "#D08770"},
	Base0A: theme.StyleDef{Foreground: "#EBCB8B"},
	Base0B: theme.StyleDef{Foreground: "#A3BE8C"},
	Base0C: theme.StyleDef{Foreground: "#88C0D0"},
	Base0D: theme.StyleDef{Foreground: "#81A1C1"},
	Base0E: theme.StyleDef{Foreground: "#B48EAD"},
	Base0F: theme.StyleDef{Foreground: "#5E81AC"},
}

// Nord contains the "Nord" base styles.
var Nord = theme.BaseStyleDefs{
	Bold: theme.StyleDef{Foreground: NordPalette.Base05.Foreground, Bold: true},
	Dim: theme.StyleDef{Foreground: NordPalette.Base03.Foreground, Faint: true},
	Italic: theme.StyleDef{Foreground: NordPalette.Base05.Foreground, Italic: true},
	Success: theme.StyleDef{Foreground: NordPalette.Base0B.Foreground, Bold: true},
	Error: theme.StyleDef{Foreground: NordPalette.Base08.Foreground, Bold: true},
	Warning: theme.StyleDef{Foreground: NordPalette.Base0A.Foreground, Bold: true},
	Info: theme.StyleDef{Foreground: NordPalette.Base0D.Foreground},
	Muted: theme.StyleDef{Foreground: NordPalette.Base04.Foreground},
	Command: theme.StyleDef{Foreground: NordPalette.Base0C.Foreground},
	Flag: theme.StyleDef{Foreground: NordPalette.Base04.Foreground},
	Heading: theme.StyleDef{Foreground: NordPalette.Base0E.Foreground, Bold: true},
	Key: theme.StyleDef{Foreground: NordPalette.Base0C.Foreground},
	Path: theme.StyleDef{Foreground: NordPalette.Base04.Foreground},
}

// SolarizedDarkPalette contains the "Solarized Dark" palette colors (base16, dark).
// Author: Ethan Schoonover (modified by aramisgithub)
var SolarizedDarkPalette = tinted.PaletteDefs{
	Base00: theme.StyleDef{Foreground: "#002b36"},
	Base01: theme.StyleDef{Foreground: "#073642"},
	Base02: theme.StyleDef{Foreground: "#586e75"},
	Base03: theme.StyleDef{Foreground: "#657b83"},
	Base04: theme.StyleDef{Foreground: "#839496"},
	Base05: theme.StyleDef{Foreground: "#93a1a1"},
	Base06: theme.StyleDef{Foreground: "#eee8d5"},
	Base07: theme.StyleDef{Foreground: "#fdf6e3"},
	Base08: theme.StyleDef{Foreground: "#dc322f"},
	Base09: theme.StyleDef{Foreground: "#cb4b16"},
	Base0A: theme.StyleDef{Foreground: "#b58900"},
	Base0B: theme.StyleDef{Foreground: "#859900"},
	Base0C: theme.StyleDef{Foreground: "#2aa198"},
	Base0D: theme.StyleDef{Foreground: "#268bd2"},
	Base0E: theme.StyleDef{Foreground: "#6c71c4"},
	Base0F: theme.StyleDef{Foreground: "#d33682"},
}

// SolarizedDark contains the "Solarized Dark" base styles.
var SolarizedDark = theme.BaseStyleDefs{
	Bold: theme.StyleDef{Foreground: SolarizedDarkPalette.Base05.Foreground, Bold: true},
	Dim: theme.StyleDef{Foreground: SolarizedDarkPalette.Base03.Foreground, Faint: true},
	Italic: theme.StyleDef{Foreground: SolarizedDarkPalette.Base05.Foreground, Italic: true},
	Success: theme.StyleDef{Foreground: SolarizedDarkPalette.Base0B.Foreground, Bold: true},
	Error: theme.StyleDef{Foreground: SolarizedDarkPalette.Base08.Foreground, Bold: true},
	Warning: theme.StyleDef{Foreground: SolarizedDarkPalette.Base0A.Foreground, Bold: true},
	Info: theme.StyleDef{Foreground: SolarizedDarkPalette.Base0D.Foreground},
	Muted: theme.StyleDef{Foreground: SolarizedDarkPalette.Base04.Foreground},
	Command: theme.StyleDef{Foreground: SolarizedDarkPalette.Base0C.Foreground},
	Flag: theme.StyleDef{Foreground: SolarizedDarkPalette.Base04.Foreground},
	Heading: theme.StyleDef{Foreground: SolarizedDarkPalette.Base0E.Foreground, Bold: true},
	Key: theme.StyleDef{Foreground: SolarizedDarkPalette.Base0C.Foreground},
	Path: theme.StyleDef{Foreground: SolarizedDarkPalette.Base04.Foreground},
}

// SolarizedLightPalette contains the "Solarized Light" palette colors (base16, light).
// Author: Ethan Schoonover (modified by aramisgithub)
var SolarizedLightPalette = tinted.PaletteDefs{
	Base00: theme.StyleDef{Foreground: "#fdf6e3"},
	Base01: theme.StyleDef{Foreground: "#eee8d5"},
	Base02: theme.StyleDef{Foreground: "#93a1a1"},
	Base03: theme.StyleDef{Foreground: "#839496"},
	Base04: theme.StyleDef{Foreground: "#657b83"},
	Base05: theme.StyleDef{Foreground: "#586e75"},
	Base06: theme.StyleDef{Foreground: "#073642"},
	Base07: theme.StyleDef{Foreground: "#002b36"},
	Base08: theme.StyleDef{Foreground: "#dc322f"},
	Base09: theme.StyleDef{Foreground: "#cb4b16"},
	Base0A: theme.StyleDef{Foreground: "#b58900"},
	Base0B: theme.StyleDef{Foreground: "#859900"},
	Base0C: theme.StyleDef{Foreground: "#2aa198"},
	Base0D: theme.StyleDef{Foreground: "#268bd2"},
	Base0E: theme.StyleDef{Foreground: "#6c71c4"},
	Base0F: theme.StyleDef{Foreground: "#d33682"},
}

// SolarizedLight contains the "Solarized Light" base styles.
var SolarizedLight = theme.BaseStyleDefs{
	Bold: theme.StyleDef{Foreground: SolarizedLightPalette.Base05.Foreground, Bold: true},
	Dim: theme.StyleDef{Foreground: SolarizedLightPalette.Base03.Foreground, Faint: true},
	Italic: theme.StyleDef{Foreground: SolarizedLightPalette.Base05.Foreground, Italic: true},
	Success: theme.StyleDef{Foreground: SolarizedLightPalette.Base0B.Foreground, Bold: true},
	Error: theme.StyleDef{Foreground: SolarizedLightPalette.Base08.Foreground, Bold: true},
	Warning: theme.StyleDef{Foreground: SolarizedLightPalette.Base0A.Foreground, Bold: true},
	Info: theme.StyleDef{Foreground: SolarizedLightPalette.Base0D.Foreground},
	Muted: theme.StyleDef{Foreground: SolarizedLightPalette.Base04.Foreground},
	Command: theme.StyleDef{Foreground: SolarizedLightPalette.Base0C.Foreground},
	Flag: theme.StyleDef{Foreground: SolarizedLightPalette.Base04.Foreground},
	Heading: theme.StyleDef{Foreground: SolarizedLightPalette.Base0E.Foreground, Bold: true},
	Key: theme.StyleDef{Foreground: SolarizedLightPalette.Base0C.Foreground},
	Path: theme.StyleDef{Foreground: SolarizedLightPalette.Base04.Foreground},
}

// Schemes maps scheme names to their style+palette vars.
var Schemes = map[string]struct {
	Styles  *theme.BaseStyleDefs
	Palette *tinted.PaletteDefs
}{
	"catppuccin-mocha": {&CatppuccinMocha, &CatppuccinMochaPalette},
	"dracula": {&Dracula, &DraculaPalette},
	"nord": {&Nord, &NordPalette},
	"solarized-dark": {&SolarizedDark, &SolarizedDarkPalette},
	"solarized-light": {&SolarizedLight, &SolarizedLightPalette},
}

// SchemeNames returns sorted scheme names from Schemes.
func SchemeNames() []string {
	names := make([]string, 0, len(Schemes))
	for name := range Schemes {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
