// Command lipmark-tinted generates Go source files from tinted-theming color schemes.
//
// Usage:
//
//	lipmark-tinted generate [-pkg name] [-tinted-pkg import] [-o file] <scheme>...
//
// The tool fetches each scheme from tinted-theming (tries base24 first, then base16),
// converts it to theme.StyleDef map literals using the default mapping, and writes
// a Go source file.
//
// Use with go:generate:
//
//	//go:generate go run github.com/pmarschik/lipmark/cmd/lipmark-tinted generate -pkg embedded -export -tinted-pkg github.com/pmarschik/lipmark/theme/tinted -o schemes_gen.go catppuccin-mocha dracula nord solarized-dark solarized-light
package main

import (
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/pmarschik/lipmark/theme/tinted"
	"gopkg.in/yaml.v3"
)

const (
	branch    = "spec-0.11"
	base24URL = "https://raw.githubusercontent.com/tinted-theming/schemes/" + branch + "/base24/"
	base16URL = "https://raw.githubusercontent.com/tinted-theming/schemes/" + branch + "/base16/"
)

type scheme struct {
	Palette map[string]string `yaml:"palette"`
	System  string            `yaml:"system"`
	Name    string            `yaml:"name"`
	Author  string            `yaml:"author"`
	Variant string            `yaml:"variant"`
}

// styleMapping describes how a style field maps to a palette key and attributes.
type styleMapping struct {
	palette string
	bold    bool
	faint   bool
	italic  bool
	uline   bool
}

// buildMappingFromDefault builds the style mapping from [tinted.DefaultMapping].
func buildMappingFromDefault() map[string]styleMapping {
	dm := tinted.DefaultMapping()
	v := reflect.ValueOf(dm)
	t := v.Type()

	m := make(map[string]styleMapping, t.NumField())
	for i := range t.NumField() {
		field := t.Field(i)
		palette := v.Field(i).String()
		if palette == "" {
			continue
		}
		key := strings.ToLower(field.Name[:1]) + field.Name[1:]
		sm := styleMapping{palette: palette}
		switch key {
		case "bold":
			sm.bold = true
		case "dim":
			sm.faint = true
		case "italic":
			sm.italic = true
		case "underline":
			sm.uline = true
		case "success", "error", "warning", "heading":
			sm.bold = true
		}
		m[key] = sm
	}
	return m
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	if len(os.Args) < 2 {
		return errors.New("usage: lipmark-tinted generate [-pkg name] [-tinted-pkg import] [-o file] <scheme>")
	}

	switch os.Args[1] {
	case "generate":
		return cmdGenerate(os.Args[2:])
	case "fetch":
		return cmdFetch(os.Args[2:])
	default:
		return fmt.Errorf("unknown command %q", os.Args[1])
	}
}

type genConfig struct {
	pkg       string
	tintedPkg string // import path for the tinted types package; empty means same package
	export    bool
}

// needsTintedImport returns true when the generated code is in a different package
// from tinted and must qualify types with the tinted package prefix.
func (c genConfig) needsTintedImport() bool {
	return c.tintedPkg != ""
}

// tintedPrefix returns the qualifier for tinted types (e.g. "tinted.").
func (c genConfig) tintedPrefix() string {
	if c.needsTintedImport() {
		return "tinted."
	}
	return ""
}

func (c genConfig) ident(name string) string {
	if c.export {
		return strings.ToUpper(name[:1]) + name[1:]
	}
	return strings.ToLower(name[:1]) + name[1:]
}

func cmdGenerate(args []string) error {
	cfg := genConfig{pkg: "tinted", export: true}
	outFile := ""
	var names []string

	for i := 0; i < len(args); i++ {
		switch args[i] {
		case "-pkg":
			if i+1 >= len(args) {
				return errors.New("-pkg requires a value")
			}
			i++
			cfg.pkg = args[i]
		case "-tinted-pkg":
			if i+1 >= len(args) {
				return errors.New("-tinted-pkg requires a value")
			}
			i++
			cfg.tintedPkg = args[i]
		case "-o":
			if i+1 >= len(args) {
				return errors.New("-o requires a value")
			}
			i++
			outFile = args[i]
		case "-export":
			cfg.export = true
		case "-no-export":
			cfg.export = false
		default:
			names = append(names, args[i])
		}
	}

	if len(names) == 0 {
		return errors.New("at least one scheme name is required")
	}

	sort.Strings(names)

	var out io.Writer = os.Stdout
	if outFile != "" {
		f, err := os.Create(outFile) //nolint:gosec // output file from flag
		if err != nil {
			return fmt.Errorf("create %s: %w", outFile, err)
		}
		defer f.Close()
		out = f
	}

	return generate(out, cfg, names)
}

func generate(w io.Writer, cfg genConfig, names []string) error {
	mapping := buildMappingFromDefault()

	fmt.Fprintf(w, "// Code generated by lipmark-tinted; DO NOT EDIT.\n\n")
	fmt.Fprintf(w, "package %s\n\n", cfg.pkg)
	fmt.Fprintf(w, "import (\n")
	fmt.Fprintf(w, "\t\"sort\"\n\n")
	fmt.Fprintf(w, "\t\"github.com/pmarschik/lipmark/theme\"\n")
	if cfg.needsTintedImport() {
		fmt.Fprintf(w, "\t\"github.com/pmarschik/lipmark/theme/tinted\"\n")
	}
	fmt.Fprintf(w, ")\n\n")

	tp := cfg.tintedPrefix()

	// Generate each scheme as two vars: Palette and Styles.
	for _, name := range names {
		s, err := fetchSchemeData(name)
		if err != nil {
			return fmt.Errorf("fetch %s: %w", name, err)
		}
		generateScheme(w, cfg, name, s, mapping, tp)
	}

	schemesVar := cfg.ident("schemes")
	schemeNamesFunc := cfg.ident("schemeNames")

	// Generate the schemes map.
	fmt.Fprintf(w, "// %s maps scheme names to their style+palette vars.\n", schemesVar)
	fmt.Fprintf(w, "var %s = map[string]struct {\n", schemesVar)
	fmt.Fprintf(w, "\tStyles  *theme.BaseStyleDefs\n")
	fmt.Fprintf(w, "\tPalette *%sPaletteDefs\n", tp)
	fmt.Fprintf(w, "}{\n")
	for _, name := range names {
		varBase := schemeToVar(name, cfg.export)
		fmt.Fprintf(w, "\t%q: {&%s, &%sPalette},\n", name, varBase, varBase)
	}
	fmt.Fprintf(w, "}\n\n")

	// Generate schemeNames function.
	fmt.Fprintf(w, "// %s returns sorted scheme names from %s.\n", schemeNamesFunc, schemesVar)
	fmt.Fprintf(w, "func %s() []string {\n", schemeNamesFunc)
	fmt.Fprintf(w, "\tnames := make([]string, 0, len(%s))\n", schemesVar)
	fmt.Fprintf(w, "\tfor name := range %s {\n", schemesVar)
	fmt.Fprintf(w, "\t\tnames = append(names, name)\n")
	fmt.Fprintf(w, "\t}\n")
	fmt.Fprintf(w, "\tsort.Strings(names)\n")
	fmt.Fprintf(w, "\treturn names\n")
	fmt.Fprintf(w, "}\n")

	return nil
}

func generateScheme(w io.Writer, cfg genConfig, name string, s *scheme, mapping map[string]styleMapping, tp string) {
	varBase := schemeToVar(name, cfg.export)

	// Palette var.
	fmt.Fprintf(w, "// %sPalette contains the %q palette colors (%s, %s).\n", varBase, s.Name, s.System, s.Variant)
	if s.Author != "" {
		fmt.Fprintf(w, "// Author: %s\n", s.Author)
	}
	fmt.Fprintf(w, "var %sPalette = %sPaletteDefs{\n", varBase, tp)
	generatePaletteFields(w, s)
	fmt.Fprintf(w, "}\n\n")

	// Styles var referencing palette fields.
	fmt.Fprintf(w, "// %s contains the %q base styles.\n", varBase, s.Name)
	fmt.Fprintf(w, "var %s = theme.BaseStyleDefs{\n", varBase)
	generateBaseStyleFields(w, varBase, s, mapping)
	fmt.Fprintf(w, "}\n\n")
}

// baseStyleFieldMap maps BaseStyleDefs field names to their mapping keys.
var baseStyleFieldMap = []struct {
	field   string
	mapping string
}{
	{"Bold", "bold"},
	{"Dim", "dim"},
	{"Italic", "italic"},
	{"Underline", "underline"},
	{"Success", "success"},
	{"Error", "error"},
	{"Warning", "warning"},
	{"Info", "info"},
	{"Muted", "muted"},
	{"Command", "command"},
	{"Flag", "flag"},
	{"Heading", "heading"},
	{"Key", "key"},
	{"Value", "value"},
	{"Path", "path"},
}

// paletteKeyToField maps palette keys like "base05" to PaletteDefs field names like "Base05".
var paletteKeyToField = map[string]string{
	"base00": "Base00", "base01": "Base01", "base02": "Base02", "base03": "Base03",
	"base04": "Base04", "base05": "Base05", "base06": "Base06", "base07": "Base07",
	"base08": "Base08", "base09": "Base09", "base0A": "Base0A", "base0B": "Base0B",
	"base0C": "Base0C", "base0D": "Base0D", "base0E": "Base0E", "base0F": "Base0F",
	"base10": "Base10", "base11": "Base11", "base12": "Base12", "base13": "Base13",
	"base14": "Base14", "base15": "Base15", "base16": "Base16", "base17": "Base17",
}

func generateBaseStyleFields(w io.Writer, varBase string, s *scheme, mapping map[string]styleMapping) {
	for _, f := range baseStyleFieldMap {
		m, ok := mapping[f.mapping]
		if !ok {
			continue
		}
		if _, hasPal := s.Palette[m.palette]; !hasPal {
			continue
		}
		palField, ok := paletteKeyToField[m.palette]
		if !ok {
			continue
		}
		attrs := renderAttrs(m.bold, m.faint, m.italic, m.uline)
		fmt.Fprintf(w, "\t%s: theme.StyleDef{Foreground: %sPalette.%s.Foreground%s},\n",
			f.field, varBase, palField, attrs)
	}
}

// paletteFieldMap maps PaletteDefs field names to palette keys.
var paletteFieldMap = []struct {
	field string
	key   string
}{
	{"Base00", "base00"},
	{"Base01", "base01"},
	{"Base02", "base02"},
	{"Base03", "base03"},
	{"Base04", "base04"},
	{"Base05", "base05"},
	{"Base06", "base06"},
	{"Base07", "base07"},
	{"Base08", "base08"},
	{"Base09", "base09"},
	{"Base0A", "base0A"},
	{"Base0B", "base0B"},
	{"Base0C", "base0C"},
	{"Base0D", "base0D"},
	{"Base0E", "base0E"},
	{"Base0F", "base0F"},
	{"Base10", "base10"},
	{"Base11", "base11"},
	{"Base12", "base12"},
	{"Base13", "base13"},
	{"Base14", "base14"},
	{"Base15", "base15"},
	{"Base16", "base16"},
	{"Base17", "base17"},
}

func generatePaletteFields(w io.Writer, s *scheme) {
	for _, f := range paletteFieldMap {
		color, ok := s.Palette[f.key]
		if !ok {
			continue
		}
		fmt.Fprintf(w, "\t%s: theme.StyleDef{Foreground: %q},\n", f.field, color)
	}
}

func renderAttrs(bold, faint, italic, uline bool) string {
	var parts []string
	if bold {
		parts = append(parts, "Bold: true")
	}
	if faint {
		parts = append(parts, "Faint: true")
	}
	if italic {
		parts = append(parts, "Italic: true")
	}
	if uline {
		parts = append(parts, "Underline: true")
	}
	if len(parts) == 0 {
		return ""
	}
	return ", " + strings.Join(parts, ", ")
}

func schemeToVar(name string, export bool) string {
	// Convert "catppuccin-mocha" to "CatppuccinMocha" (exported) or "catppuccinMocha" (unexported).
	parts := strings.Split(name, "-")
	for i, p := range parts {
		if p != "" {
			if i == 0 && !export {
				parts[i] = strings.ToLower(p[:1]) + p[1:]
			} else {
				parts[i] = strings.ToUpper(p[:1]) + p[1:]
			}
		}
	}
	return strings.Join(parts, "")
}

func fetchSchemeData(name string) (*scheme, error) {
	safe, err := sanitizeName(name)
	if err != nil {
		return nil, err
	}
	filename := safe + ".yaml"
	for _, baseURL := range []string{base24URL, base16URL} {
		resp, httpErr := http.Get(baseURL + filename) //nolint:gosec,noctx // CLI tool
		if httpErr != nil {
			continue
		}
		if resp.StatusCode != http.StatusOK {
			resp.Body.Close()
			continue
		}
		var s scheme
		decErr := yaml.NewDecoder(resp.Body).Decode(&s)
		resp.Body.Close()
		if decErr != nil {
			return nil, fmt.Errorf("decode %s: %w", name, decErr)
		}
		fmt.Fprintf(os.Stderr, "Fetched %s (%s, %s)\n", name, s.System, s.Variant)
		return &s, nil
	}
	return nil, fmt.Errorf("scheme %q not found", safe)
}

// cmdFetch downloads a raw YAML scheme file (for apps that want runtime loading).
func cmdFetch(args []string) error {
	if len(args) < 1 {
		return errors.New("fetch requires a scheme name")
	}
	name := args[0]
	dir := "."
	for i := 1; i < len(args); i++ {
		if args[i] == "-o" && i+1 < len(args) {
			dir = args[i+1]
			i++
		}
	}
	return fetchYAML(name, dir)
}

func fetchYAML(name, dir string) error {
	safe, err := sanitizeName(name)
	if err != nil {
		return err
	}
	filename := safe + ".yaml"
	for _, baseURL := range []string{base24URL, base16URL} {
		resp, httpErr := http.Get(baseURL + filename) //nolint:gosec,noctx // CLI tool
		if httpErr != nil {
			continue
		}
		if resp.StatusCode != http.StatusOK {
			resp.Body.Close()
			continue
		}
		outPath := filepath.Join(dir, filename)
		f, createErr := os.Create(outPath) //nolint:gosec // sanitized
		if createErr != nil {
			resp.Body.Close()
			return fmt.Errorf("create %s: %w", outPath, createErr)
		}
		_, copyErr := io.Copy(f, resp.Body)
		f.Close()
		resp.Body.Close()
		if copyErr != nil {
			return fmt.Errorf("write %s: %w", outPath, copyErr)
		}
		fmt.Fprintf(os.Stderr, "Downloaded %s to %s\n", safe, outPath)
		return nil
	}
	return fmt.Errorf("scheme %q not found", safe)
}

func sanitizeName(name string) (string, error) {
	clean := filepath.Base(name)
	if clean != name || strings.ContainsAny(name, `/\`) || name == "." || name == ".." {
		return "", fmt.Errorf("invalid scheme name %q", name)
	}
	return clean, nil
}
